name: Publish Python distribution to PyPI and TestPyPI
on: push
 
jobs:
  build-n-publish:
    name: Publish Python distribution to PyPI and TestPyPI
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - name: Setup Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install pep517
        run: >-
          python -m
          pip install
          pep517
          --user
      - name: Build a binary wheel and a source tarball
        run: >-
          python -m
          pep517.build
          --source
          --binary
          --out-dir dist/
      - name: Publish distribution to TestPyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.pypi_password }}
          repository_url: https://test.pypi.org/legacy/
      
